### PR TITLE
Feature/friendships- Milestone-2

### PR DESCRIPTION
**Pull request by Div685**
# This is a Milestone 2 for social-Media app
In this PR, we implemented friendship features. some of the functionalities are listed below:
- we added a friendship model
- we added friendship associations
- we added the Rspec unit and integrations testing for the user, post, friendship, comment, and like.

kindly review.

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS : CHANGES REQUIRED :red_circle: :recycle: 
Hey team @Div685 and @Adewunmi97 :wave: :wave:  Your project's implementation is almost done, you have started well, your tests, controllers, and models, views are working as expected. However, a few things need to be implemented as mentioned below

- [x] User model` has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id" `
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) Take a minute and refer to this [LINK](https://smartfunnycool.com/friendships-in-activerecord/) for more readings

- [x] When I run your RSpec tests, some tests are failing while two are passing. I will attach a screenshot for this
Pending tests
image

Failing Tests
image

image


Thats all :smile: , Kindly submit another review when done

Regards
Peris Ndanu
Feel free to slack me if you have any questions.

**Comment by Div685** [comment]
Thanks for the quick review and your time @mimipeshy, I'm not sure why tests are failing on your side while in my machine all the tests are passing. Here are screenshots from my pc. 
Screenshot from 2021-01-18 15-30-10
Screenshot from 2021-01-18 15-31-25
Screenshot from 2021-01-18 15-32-08

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] The tests are still failing. This is related to the Session controller Spec, if run the test individually all pass except for that one, and is related to the user session so when RSpec runs the test as it runs it first it messes with everything else. Please review the implementation and submit it for re-review.
image

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by mimipeshy** [comment]
### STATUS : CHANGES REQUESTED :red_circle: :recycle: 

Hey team @Div685 and @Adewunmi97 :wave: :wave: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
 I liked that you have tried to implement the requested changes from the previous review, keep it up, and your project is really almost done. 
However, two more tests are still failing. Check out the screenshot below :arrow_down: 
image
image

Thats all :smile: , Kindly submit another review when done

Regards
Peris Ndanu
Feel free to slack me if you have any questions.

**Comment by Div685** [comment]
Hello, 
Thanks for the review, But all the tests are passing on my side. Can you please confirm again or show me how you are running the RSpec tests.
please Try running RSpec with an `order defined` flag if possible. 
` rspec --order defined --format documentation ` 
Thanks kindly check my result as a screenshot. I appreciate your support. 
Screenshot from 2021-01-18 20-15-37
Screenshot from 2021-01-18 20-15-48.

**Review by SpaYco — APPROVED** [review]
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Pull request merged**
